### ISSUE TITLE
The QwaterModel v.1.3 does not work in QGIS version 3.22.1

### ISSUE THREAD

**Issue by taras-user** [FloEll/QWaterModel#6]
the QwaterModel v.1.3 does not work in QGIS version 3.22.1. I present the error text.
`ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/__init__.py", line 35, in classFactory
    from .qwatermodel import QWaterModel
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/qwatermodel.py", line 48, in 
    import gdal
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

Python: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0] 
QGIS: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

Python:
/usr/share/qgis/python
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/taras/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python
`

**Comment by FloEll** [comment]
Hi taras-user,

thanks for your email. Your error is a quite common one. You most likely installed a QGIS3 version without the gdal-package. If this package is missing, you will get this error: `ModuleNotFoundError: No module named 'gdal'

The simplest solution to make the QWaterModel plugin run, is to re-install QGIS3 with the full OSGeo4W environment e.g. via the OSGeo4W Network Installer: https://www.qgis.org/en/site/forusers/download.html if you are using Windows. Installing QGIS3 via the OSGeo4W Network Installer will automatically install the gdal package. 

I think it should work after a re-installation. If it still doesn't work, please write me again and we can see if we can fix your problem. 

Cheers,
Florian

**Comment by taras-user** [comment]
Thanks for the quick response.
I am using ubuntu 20.04 and I have the latest version of gdal installed
ogrinfo --version
GDAL 3.3.2, released 2021/09/01
With best wishes, Taras

**Comment by FloEll** [comment]
Hi Taras, 
ok, great. Sounds good. Does it work for you now or do you still encounter problems? 
Cheers,
Florian

**Comment by taras-user** [comment]
Yes, the plugin does not find gdal and gives an error
`Failed to load the 'qwatermodel' module due to an error when calling the iclassfactory() method
ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/__init__.py", line 35, in classFactory
    from .qwatermodel import QWaterModel
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/qwatermodel.py", line 48, in 
    import gdal
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'


 Python: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0] 
QGIS: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

 Python Location:
/usr/share/qgis/python
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/taras/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python
.
/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/libs`

`CRITICAL    Traceback (most recent call last):
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/__init__.py", line 35, in classFactory
              from .qwatermodel import QWaterModel
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/qwatermodel.py", line 48, in 
              import gdal
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'gdal'`

**Comment by FloEll** [comment]
Dear Taras,
I must confess that I'm not very experienced with Ubuntu. I remember there was a very simple way of installing QGIS 3 via a Software Center (not via a terminal), but that installation would not install all the required software packages (such as gdal) and it would not come with the OSGeo4W (which was the root of many problems). 

Since you installed the gdal package on a python kernel, it should be detected and not give the ModuleNotFoundError. I think this is a really interesting error and I would really like to help you here. Did you install the gdal package via the OSGeo4W shell or via another shell in Linux? Do you maybe have other python 3 kernels running on your system (e.g. in conda or by another python IDE)? 

I'm currently quite busy, but I could try to replicate this error on the weekend if this is not too late for you? 

Cheers,
Florian

**Comment by ibreckhe** [comment]
Hi Florian,

Just a note that I also encountered this issue with QGIS 3.22.1 (on both Mac and Windows platforms). Downgrading to version 3.14 allowed me to successfully install the plugin on Windows. Here's the error on MacOS. Note that GDAL-3.3.2 appears in the Python path.

Couldn't load plugin 'qwatermodel' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
```
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/ian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/__init__.py", line 35, in classFactory
    from .qwatermodel import QWaterModel
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/qwatermodel.py", line 48, in 
    import gdal
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'
```


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/ian/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/ian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/ian/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/ian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/FeatureGridCreator

**Comment by FloEll** [comment]
Dear Ian, 
thank you for your message and for posting the error details. This is quite strange, I hope I can reproduce this here. I'm quite busy today, but I'll try to figure out what happened here on the weekend. 
Cheers,
Florian

**Comment by FloEll** [comment]
Hi there,
sorry it took quite a bit of time, but I found a solution that should fix it:

Please open QGIS3 (I use version 3.22.1 now).

Then go to **Settings>Options>System**

Scroll down to **Environment** 

In **Environment** enable **Use custom variables (restart required ...)** 

Then scroll down to **PATH** and enter this as the path:
/Library/Frameworks/GDAL.framework/Programs:/Library/Frameworks/Python.framework/Versions/3.6/bin:

After restarting QGIS it should work without errors. 

Please tell me if it worked for you.
